In [1]:
#### ASSIGNMENT

In [7]:
###QUESTION 1 - Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
y=np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
### QUESTION 2 - Create a vector with values ranging from 10 to 49

import numpy as np
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
### QUESTION 3 - Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
### QUESTION 4 -  Find indices of non-zero elements from [1,2,0,0,4,0]

import numpy as np
arr = [1,2,0,0,4,0]
x = np.nonzero(arr)
print(x)

(array([0, 1, 4], dtype=int64),)


In [23]:
### QUESTION 5 - Create a 10x10 array with random values and find the minimum and maximum values

import numpy as np
arr = np.random.random((10,10))
print(arr)
min_of_arr = arr.min()
max_of_arr = arr.max()
print('Max of array is : ',max_of_arr)
print('Min of array is : ',min_of_arr)

[[0.30584912 0.32094681 0.68801972 0.73923092 0.93279452 0.39764084
  0.48616455 0.18115439 0.82486423 0.2206549 ]
 [0.08411462 0.18473555 0.37618725 0.17795647 0.87312235 0.6701918
  0.76345195 0.04303151 0.49027347 0.35842088]
 [0.00977747 0.56059865 0.52144808 0.21030424 0.19057228 0.86504672
  0.47878142 0.69972065 0.60903104 0.54404862]
 [0.07614558 0.64895446 0.78253957 0.698088   0.32450687 0.07433647
  0.53051541 0.28285151 0.95636683 0.60652794]
 [0.56342429 0.49442801 0.47357008 0.52394214 0.79482053 0.54439515
  0.85484028 0.28947538 0.75149198 0.73387186]
 [0.38207124 0.16158523 0.23124164 0.83058356 0.20486857 0.3660033
  0.12403652 0.41001007 0.93301687 0.98135376]
 [0.50592901 0.15352339 0.66069386 0.502564   0.71274246 0.34012225
  0.1399791  0.83308591 0.6346247  0.24332478]
 [0.41579326 0.38544988 0.54027789 0.1026846  0.97513008 0.59950182
  0.96944617 0.77166628 0.59774823 0.00718244]
 [0.78576969 0.14672559 0.44518294 0.73891361 0.57442274 0.60120036
  0.98690904 0

In [28]:
### QUESTION 6 - Create a random vector of size 30 and find the mean value

import numpy as np
x = np.random.random(10)
print(x)
mean = x.mean()
print("Mean of array is : ",mean)

[0.98543099 0.89942748 0.71866149 0.14276851 0.22124088 0.91620971
 0.12542687 0.04577899 0.49729085 0.5414177 ]
Mean of array is :  0.5093653482667742
